### ISSUE TITLE
Flawed - exists as if ipv6 doesn't exist

### ISSUE THREAD

**Issue by sectary-want-holly** [GianlucaUlivi/CheckMK-DDNS-Check#3]
As per $subject. This script is flawed as it has *zero* consideration for v6 addresses.

**Comment by GianlucaUlivi** [comment]
Hi @sectary-want-holly,
You are more than welcome to put your PR if you want to implement IPv6.  

At the moment IPv6 is not in scope as any semi-decent ISP that provides IPv6 will not do shady tactics to prevent you to have a static public IPv6, at least not here were I am located.  

If you need to check the IPv6 as well you are more than welcome to implement it by starting from this base and add your own code, this is the magic of open source ;).  

I would also like to point out that, even if it was not tested for IPv6, it should actually work anyway as ifconfig.me does support IPv6 and will give you your IPv6 as reply if you contact it via IPv6, and the reply for your DNS query depends on the DDNS provider you are using, and they should also support IPv6.

**Comment by sectary-want-holly** [comment]
> At the moment IPv6 is not in scope as any semi-decent ISP that provides IPv6 will not do shady tactics to prevent you to have a static public IPv6, at least not here were I am located.

I know of no major US ISP that provides static IPs for residential service, let alone providing a static v6 delegation. You're in dream world. 

> I would also like to point out that, even if it was not tested for IPv6, it should actually work anyway

You don't understand v6. The local v6 address of the server will be returned *not* the DDNS v6 IP configured. Sigh...

**Comment by GianlucaUlivi** [comment]
> I know of no major US ISP that provides static IPs for residential service, let alone providing a static v6 delegation. You're in dream world.

Were I currently live the few ISP that do provide IPv6 will provide it statically, unfortunately it's not the dream world.  

> You don't understand v6. The local v6 address of the server will be returned not the DDNS v6 IP configured. Sigh...

It should actually depend on your DDNS configuration, if the DDNS agent and the script are run on the same host the result should be the same.  

As I pointed out previously, you are free to put in a PR or branch out this script and add your own code to make IPv6 check works as you want, since you clearly to understand IPv6 so much that should be easy.
